In [1]:
!pip install SPARQLWrapper
!pip install sparql-dataframe

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: SPARQLWrapper in c:\users\niklasdörner\appdata\roaming\python\python312\site-packages (2.0.0)
Requirement already satisfied: rdflib>=6.1.1 in c:\users\niklasdörner\appdata\roaming\python\python312\site-packages (from SPARQLWrapper) (7.5.0)
Requirement already satisfied: pyparsing<4,>=2.1.0 in c:\programdata\anaconda3\lib\site-packages (from rdflib>=6.1.1->SPARQLWrapper) (3.1.2)
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: sparql-dataframe in c:\users\niklasdörner\appdata\roaming\python\python312\site-packages (0.4)
Requirement already satisfied: pandas>=0.22.0 in c:\programdata\anaconda3\lib\site-packages (from sparql-dataframe) (2.2.2)
Requirement already satisfied: SPARQLWrapper>=1.8.1 in c:\users\niklasdörner\appdata\roaming\python\python312\site-packages (from sparql-dataframe) (2.0.0)
Requirement already satisfied: numpy>=1.26.0 in c:\programdata\anaconda3\lib\site-packages (from pandas>=0.22.0->sparql-dataframe) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\programdata\anaconda3\lib\site-packages (from pandas>=0.22.0->sparql-dataframe) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\programdata\anaconda3\lib\site-packages (from pandas>=0.22.0->sparql-dataframe) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\programdata\anaconda3\lib\site-packages (from pandas>=0.22.0->sparql-dataframe) (2023.3)
Requirement already satisfied: rdflib>=6.1.1 in c:\users\niklasdörner\appdata\roaming\python\python312\site-packages (from SPARQLWrapper>=1.8.1->sparql-dataframe) (7.5.0)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas>=0.22.0->sparql-dataframe) (1.16.0)
Requirement already satisfied: pyparsing<4,>=2.1.0 in c:\programdata\anaconda3\lib\site-packages (from rdflib>=6.1.1->SPARQLWrapper>=1.8.1->sparql-dataframe) (3.1.2)

In [5]:
import sparql_dataframe

endpoint = "http://localhost:7200/repositories/mqtt4ssn"

In [6]:
NS = {
    "mqtt:": "https://doernern.github.io/MQTT4SSNOntology/MQTT4SSN.owl#",
    "rdfs:": "http://www.w3.org/2000/01/rdf-schema#",
    "ex:": "http://example.org/",
    "sosa": "http://www.w3.org/ns/sosa/" 
}

In [7]:
import pandas as pd

def strip_namespaces(df, ns_map=NS):
    def shrink(val):
        if not isinstance(val, str):
            return val
        # ersetze bekannte Namespaces durch Prefix
        for pref, base in ns_map.items():
            if val.startswith(base):
                return pref + val[len(base):]
        # fallback: nur local name nach # oder /
        if "#" in val:
            return val.rsplit("#", 1)[-1]
        if "/" in val:
            return val.rsplit("/", 1)[-1]
        return val

    return df.map(shrink)

## Control Packet Hierachy

### CQ1.01g - What types of COntrol Packets exists ?

In [8]:
q = """

PREFIX mqtt: <https://doernern.github.io/MQTT4SSNOntology/MQTT4SSN.owl#>
PREFIX mqv: <https://www.w3.org/2019/wot/mqtt#> 

SELECT ?type WHERE {
  ?type rdfs:subClassOf mqtt:ControlPacket .

    FILTER( STRSTARTS(STR(?type), STR(mqtt:)) )
}

"""

df = sparql_dataframe.get(endpoint, q)
df_short = strip_namespaces(df)
df_short

                      type
0          mqtt:AuthPacket
1       mqtt:ConnackPacket
2       mqtt:ConnectPacket
3    mqtt:DisconnectPacket
4       mqtt:ControlPacket
5       mqtt:PingreqPacket
6      mqtt:PingrespPacket
7        mqtt:PubackPacket
8       mqtt:PubcompPacket
9       mqtt:PublishPacket
10       mqtt:PubrecPacket
11       mqtt:PubrelPacket
12       mqtt:SubackPacket
13    mqtt:SubscribePacket
14     mqtt:UnsubackPacket
15  mqtt:UnsubscribePacket

### CQ1.02g - Which Control Packets has a fixed / Variable Header or Payload ?

In [18]:
q = """

PREFIX mqtt: <https://doernern.github.io/MQTT4SSNOntology/MQTT4SSN.owl#>
PREFIX sosa: <http://www.w3.org/ns/sosa/> 


SELECT ?type ?relation ?entity WHERE {
  ?type rdfs:subClassOf mqtt:ControlPacket .
  ?relation rdfs:range ?type ;
       rdfs:domain ?entity .
  FILTER( STRSTARTS(STR(?relation), STR(mqtt:)) ) .
  FILTER( STRSTARTS(STR(?entity), STR(mqtt:)) )

}

"""

df = sparql_dataframe.get(endpoint, q)
df_short = strip_namespaces(df)
df_short

,type,relation,entity
0,mqtt:AuthPacket,mqtt:isAuthVariableHeaderOf,mqtt:AuthVariableHeader
1,mqtt:AuthPacket,mqtt:isAuthFixedHeaderOf,mqtt:AuthFixedHeader
2,mqtt:ConnackPacket,mqtt:isConnackVariableHeaderOf,mqtt:ConnackVariableHeader
3,mqtt:ConnackPacket,mqtt:isConnackFixedHeaderOf,mqtt:ConnackFixedHeader
4,mqtt:ConnackPacket,mqtt:receivesConnackPacket,mqtt:Client
5,mqtt:ConnackPacket,mqtt:sendsConnackPacket,mqtt:Broker
6,mqtt:ConnectPacket,mqtt:isConnectFixedHeaderOf,mqtt:ConnectFixedHeader
7,mqtt:ConnectPacket,mqtt:isConnectPayloadOf,mqtt:ConnectPayload
8,mqtt:ConnectPacket,mqtt:isConnectVariableHeaderOf,mqtt:ConnectVariableHeader
9,mqtt:ConnectPacket,mqtt:receivesConnectPacket,mqtt:Broker
10,mqtt:ConnectPacket,mqtt:sendsConnectPacket,mqtt:Client
11,mqtt:DisconnectPacket,mqtt:isDisconnectVariableHeaderOf,mqtt:DisconnectVariableHeader
12,mqtt:DisconnectPacket,mqtt:isDisconnectFixedHeaderOf,mqtt:DisconnectFixedHeader
13,mqtt:ControlPacket,mqtt:isFixedHeaderOf,mqtt:FixedHeader
14,mqtt:ControlPacket,mqtt:isPayloadOf,mqtt:Payload
15,mqtt:ControlPacket,mqtt:isVariableHeaderOf,mqtt:VariableHeader
16,mqtt:PingreqPacket,mqtt:isPingreqFixedHeaderOf,mqtt:PingreqFixedHeader
17,mqtt:PingreqPacket,mqtt:receivesPingreqPacket,mqtt:Client
18,mqtt:PingreqPacket,mqtt:sendsPingreqPacket,mqtt:Client
19,mqtt:PingrespPacket,mqtt:isPingrespFixedHeaderOf,mqtt:PingrespFixedHeader
20,mqtt:PingrespPacket,mqtt:receivesPingrespPacket,mqtt:Broker
21,mqtt:PingrespPacket,mqtt:sendsPingrespPacket,mqtt:Broker
22,mqtt:PubackPacket,mqtt:isPubackVariableHeaderOf,mqtt:PubackVariableHeader
23,mqtt:PubackPacket,mqtt:isPubackFixedHeaderOf,mqtt:PubackFixedHeader
24,mqtt:PubcompPacket,mqtt:isPubcompVariableHeaderOf,mqtt:PubcompVariableHeader
25,mqtt:PubcompPacket,mqtt:isPubcompFixedHeaderOf,mqtt:PubcompFixedHeader
26,mqtt:PublishPacket,mqtt:isPublishFixedHeaderOf,mqtt:PublishFixedHeader
27,mqtt:PublishPacket,mqtt:isPublishPayloadOf,mqtt:PublishPayload
28,mqtt:PublishPacket,mqtt:isPublishVariableHeaderOf,mqtt:PublishVariableHeader
29,mqtt:PubrecPacket,mqtt:isPubrecVariableHeaderOf,mqtt:PubrecVariableHeader
30,mqtt:PubrecPacket,mqtt:isPubrecFixedHeaderOf,mqtt:PubrecFixedHeader
31,mqtt:PubrelPacket,mqtt:isPubrelVariableHeaderOf,mqtt:PubrelVariableHeader
32,mqtt:PubrelPacket,mqtt:isPubrelFixedHeaderOf,mqtt:PubrelFixedHeader
33,mqtt:SubackPacket,mqtt:isSubackPayloadOf,mqtt:SubackPayload
34,mqtt:SubackPacket,mqtt:isSubackVariableHeaderOf,mqtt:SubackVariableHeader
35,mqtt:SubackPacket,mqtt:isSubackFixedHeaderOf,mqtt:SubackFixedHeader
36,mqtt:SubackPacket,mqtt:receivesSubackPacket,mqtt:Client
37,mqtt:SubackPacket,mqtt:sendsSubackPacket,mqtt:Broker
38,mqtt:SubscribePacket,mqtt:isSubscribeFixedHeaderOf,mqtt:SubscribeFixedHeader
39,mqtt:SubscribePacket,mqtt:isSubscribePayloadOf,mqtt:SubscribePayload
40,mqtt:SubscribePacket,mqtt:isSubscribeVariableHeaderOf,mqtt:SubscribeVariableHeader
41,mqtt:SubscribePacket,mqtt:receivesSubscribePacket,mqtt:Broker
42,mqtt:SubscribePacket,mqtt:sendsSubscribePacket,mqtt:Client
43,mqtt:UnsubackPacket,mqtt:isUnsubackPayloadOf,mqtt:UnsubackPayload
44,mqtt:UnsubackPacket,mqtt:isUnsubackVariableHeaderOf,mqtt:UnsubackVariableHeader
45,mqtt:UnsubackPacket,mqtt:isUnsubackFixedHeaderOf,mqtt:UnsubackFixedHeader
46,mqtt:UnsubackPacket,mqtt:receivesUnsubackPacket,mqtt:Client
47,mqtt:UnsubackPacket,mqtt:sendsUnsubackPacket,mqtt:Broker
48,mqtt:UnsubscribePacket,mqtt:isUnsubscribeFixedHeaderOf,mqtt:UnsubscribeFixedHeader
49,mqtt:UnsubscribePacket,mqtt:isUnsubscribePayloadOf,mqtt:UnsubscribePayload
50,mqtt:UnsubscribePacket,mqtt:isUnsubscribeVariableHeaderOf,mqtt:UnsubscribeVariableHeader
51,mqtt:UnsubscribePacket,mqtt:receivesUnsubscribePacket,mqtt:Broker
52,mqtt:UnsubscribePacket,mqtt:sendsUnsubscribePacket,mqtt:Client